### ISSUE TITLE
Does the react project support streaming video by ws protocol?

### ISSUE THREAD

**Issue by rogeliozx** [coding-with-chaim/react-video-chat#4]
I have a backend convert rtsp to ws and I want to use the videoplayer you have to make the ws connection and show the straming

**Comment by ChaimF90** [comment]
The react code in this app assumes socket.io, so if you want to use native websockets, you would need to make that change in the code

**Comment by rogeliozx** [comment]
If for example I have a connection ws: // localhost: 3000 / stream, could it play the streaming video if I put it in the src?

sorry for the inconvenience I have long wanted to achieve this

**Comment by ChaimF90** [comment]
No, at the moment the video players are only playing the stream that is being retrieved from the peers. The sockets in this app are there simply to facilitate the handshake between the pairs. If your goal is to play a video in the client side that is getting streamed from the server via websockets, I dont think there is much if any code that can be of use to you. Please do let me know if I have misunderstood you.

**Comment by rogeliozx** [comment]
I understood well, thank you very much for your time, sorry for the inconvenience

**Comment by ChaimF90** [comment]
No inconvenience at all!
